import UIKit

// Task
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence that do not exceed the nth term, find the sum of the even-valued terms.


func fiboEvenSum(number: Int) -> Int {
    var tupel = (1,2) // First fibonacci digits
    var sum = 2
    
    for _ in 2..<number {
        let nextFibo = tupel.0 + tupel.1
        if nextFibo % 2 == 0 {
            sum += nextFibo
        }
        tupel = (tupel.1, nextFibo)
    }
    
    return sum
}

var test = fiboEvenSum(number: 23)
